package edu.brown.cs.andrew.handlers;

public enum Commands {
  ADD_FRIEND, ACCEPT_FRIEND, REMOVE_FRIEND,
  ADD_GROUP, REMOVE_GROUP, ADD_EVENT, DELETE_EVENT, REMOVE_USER_EVENT,
  EDIT_EVENT, GET_NAME, FIND_MEMBERS;
}
